Jpty - Correction for itemhouse intrusion and Jeedom v4.4 compatibility.
fdp1nm/plugin-protexiom pull request #1
Opened 2023-07-08 21:14 UTC by jpty

2023-07-22 21:12 UTC, fdp1nm requested changes
Merci pour tes modifications.
Je te soumet 3 remarques avant de berger.

2023-07-22 21:12 UTC, fdp1nm commented on core/class/protexiom.class.php
> +        $this->log('warning', 'The following error occured while pulling elements: '.$myError.'. This may be a session timeout issue. Let\'s workaround it');
L'expiration de la session est un évènement normal qui se produit fréquemment et doit être contourné sans que ce ne soit le signe d'un problème. Je pense que ce logement doit rester en début et non en warning.

2023-07-22 21:12 UTC, fdp1nm commented on core/class/protexiom.class.php
> -/*     * **********************Getteur Setteur*************************** */
Cette section existe dans le template par défaut d'un plugin jeedom. Elle est habituellement conservée dans les plugins même si elle est vide.

2023-07-22 21:12 UTC, fdp1nm commented on core/class/protexiom.class.php
> -?>
Le tag <?PHP est ouvert en début de fichier. Il faut le fermer en fin de fichier.

2023-07-22 23:18 UTC, jpty commented on core/class/protexiom.class.php
> +        $this->log('warning', 'The following error occured while pulling elements: '.$myError.'. This may be a session timeout issue. Let\'s workaround it');
OK pour rester en debug. Ca polluera moins les logs.

2023-07-22 23:21 UTC, jpty commented on core/class/protexiom.class.php
> -/*     * **********************Getteur Setteur*************************** */
Ce n'est qu'un commentaire d'introduction d'une section qui est vide.
Ca m'étonnerait que le plugin évolue encore et ait besoin de cette section.

2023-07-22 23:26 UTC, jpty commented on core/class/protexiom.class.php
> -?>
Non, si le fichier ne contient que du PHP, la fermeture de la balise <?php est déconseillée :
[Doc PHP](https://www.php.net/manual/fr/language.basic-syntax.phptags.php)

2023-07-23 07:54 UTC, fdp1nm commented on core/class/protexiom.class.php
> -?>
OK pour moi. J'aurais appris ça ;-)

2023-07-23 09:29 UTC, merged